#!/usr/bin/env python3

from pathlib import Path
import os
import json

ROOT = Path(__file__).parent
FEATHER_ICONS = ROOT / "feather-icons"
SVG_PATH = FEATHER_ICONS / "icons"
PACKAGE_JSON = FEATHER_ICONS / "package.json"
LICENSE = FEATHER_ICONS / "LICENSE"
OUTFILE = ROOT / "feather-icons-data.typ"

HEADER = '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">'
FOOTER = '</svg>'

HEADER_WORDS = set(HEADER.split())

def is_header_equivalent(header):
    return set(HEADER.split()) == HEADER_WORDS

def escape_quotes(s: str):
    return s.replace(r'"', r'\"')

def main():

    with open(OUTFILE, "w") as f:
        def print(s): f.write(s + '\n')

        print(f'// NOTE: This file has been generated by `{Path(__file__).name}`.')
        print(f'//       It contains data from the Feather Icons source code.\n')

        print("// The LICENSE of Feather Icons has been copied here: \n")
        lines = LICENSE.read_text().splitlines()
        for line in lines:
            print(f"// {line}")
        print("")

        print(f'#let icons-version = "{json.loads(PACKAGE_JSON.read_text())['version']}"')
        print(f'#let icons-repository = "{json.loads(PACKAGE_JSON.read_text())['repository']['url']}"')

        print(f'#let header = "{escape_quotes(HEADER)}"')
        print(f'#let footer = "{escape_quotes(FOOTER)}"')

        print("#let strokes = (")

        for path in SVG_PATH.iterdir():
            name = path.stem

            svg = path.read_text()

            header = svg[:svg.find(">") + 1]

            assert(is_header_equivalent(svg))
            assert(svg.endswith(FOOTER))

            strokes = svg[len(header):-len(FOOTER)]

            print(f'  {name}: "{escape_quotes(strokes)}",')


        print(")")

if __name__ == "__main__":
    main()
