name: Pages

on:
  push:
    branches: [ "main" ]
    # paths:
    #   - report/**
    #   - botbrain/**
    #   - simple_sim/**


permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: ./docs.typ

      - name: Make `public` directory
        run: |
          mkdir -v public
          cp -v docs.pdf public
          cat << EOF > public/index.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta http-equiv="refresh" content="0; url=/docs.pdf">
            <title>Redirecting...</title>
            <script>
              window.location.href = "https://balderholst.github.io/typst-feather-icons/docs.pdf";
            </script>
          </head>
          <body>
            <p>If you are not redirected automatically, <a href="https://balderholst.github.io/typst-feather-icons/docs.pdf">click here to open the document</a>.</p>
          </body>
          </html>
          EOF

      - name: Upload Documentation Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
