name: Pages

on:
  push:
    branches: [ "main" ]


permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Typst
        uses: typst-community/setup-typst@v5

      - name: Verify Typst installation
        run: typst --version

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build Docs
        run: typst compile ./docs.typ

      - name: Build Example SVG
        run: python docs/extract-example.py | typst c - example.svg

      - name: Make `public` directory
        run: |
          mkdir -v public
          cp -v docs.pdf public
          cp -v example.svg public
          cat << EOF > public/index.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta http-equiv="refresh" content="0; url=/docs.pdf">
            <title>Redirecting...</title>
            <script>
              window.location.href = "https://balderholst.github.io/typst-feather-icons/docs.pdf";
            </script>
          </head>
          <body>
            <p>If you are not redirected automatically, <a href="https://balderholst.github.io/typst-feather-icons/docs.pdf">click here to open the document</a>.</p>
          </body>
          </html>
          EOF

      - name: Upload Documentation Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
